version: '3.7'
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "hyperf"
    networks:
      - net
    volumes:
      - ./.storage/mysql:/var/lib/mysql
      - ./.github/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - ./.storage/redis:/data
    restart: "always"
  shabao-admin:
    image: "wlfpanda1012/shabao-admin:latest"
    build:
      context: "."
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: "${APP_ENV:-prod}"
      DB_HOST: "mysql"
      REDIS_HOST: "redis"
    ports:
      - "9505:9505"
      - "9506:9506"
    volumes:
      - "./.env.example:/opt/www/.env"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1
networks:
  net:
    driver: bridge
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
