version: '3.7'
services:
  mysql:
    image: "mysql:8.0"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
    networks:
      - net
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./.github/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "13306:3306"
    restart: "always"
  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - ./.docker/redis:/data
    restart: "always"
  shabao-admin:
    image: "wlfpanda1012/web-api:8.1-alpine-v3.18-swoole-xlswriter"
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: "${APP_ENV:-prod}"
      DB_HOST: "mysql"
      REDIS_HOST: "redis"
    working_dir: "/opt/www"
    ports:
      - "9505:9505"
      - "9506:9506"
    volumes:
      - "./:/opt/www"
      - "./.env.docker:/opt/www/.env"
    networks:
      - net
    entrypoint: ["php", "watch", "-c"]
networks:
  net:
    driver: bridge
volumes:
  mysql-data:
  redis-data:
